// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: controller.proto

#ifndef PROTOBUF_controller_2eproto__INCLUDED
#define PROTOBUF_controller_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
// @@protoc_insertion_point(includes)

namespace maid {
namespace controller {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_controller_2eproto();
void protobuf_AssignDesc_controller_2eproto();
void protobuf_ShutdownFile_controller_2eproto();

class Controller;

// ===================================================================

class Controller : public ::google::protobuf::Message {
 public:
  Controller();
  virtual ~Controller();
  
  Controller(const Controller& from);
  
  inline Controller& operator=(const Controller& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const Controller& default_instance();
  
  void Swap(Controller* other);
  
  // implements Message ----------------------------------------------
  
  Controller* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Controller& from);
  void MergeFrom(const Controller& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // optional string service_name = 1;
  inline bool has_service_name() const;
  inline void clear_service_name();
  static const int kServiceNameFieldNumber = 1;
  inline const ::std::string& service_name() const;
  inline void set_service_name(const ::std::string& value);
  inline void set_service_name(const char* value);
  inline void set_service_name(const char* value, size_t size);
  inline ::std::string* mutable_service_name();
  inline ::std::string* release_service_name();
  
  // optional string method_name = 2;
  inline bool has_method_name() const;
  inline void clear_method_name();
  static const int kMethodNameFieldNumber = 2;
  inline const ::std::string& method_name() const;
  inline void set_method_name(const ::std::string& value);
  inline void set_method_name(const char* value);
  inline void set_method_name(const char* value, size_t size);
  inline ::std::string* mutable_method_name();
  inline ::std::string* release_method_name();
  
  // optional int32 transmit_id = 3;
  inline bool has_transmit_id() const;
  inline void clear_transmit_id();
  static const int kTransmitIdFieldNumber = 3;
  inline ::google::protobuf::int32 transmit_id() const;
  inline void set_transmit_id(::google::protobuf::int32 value);
  
  // optional bool stub_side = 4;
  inline bool has_stub_side() const;
  inline void clear_stub_side();
  static const int kStubSideFieldNumber = 4;
  inline bool stub_side() const;
  inline void set_stub_side(bool value);
  
  // optional bool is_canceled = 5;
  inline bool has_is_canceled() const;
  inline void clear_is_canceled();
  static const int kIsCanceledFieldNumber = 5;
  inline bool is_canceled() const;
  inline void set_is_canceled(bool value);
  
  // optional bool failed = 6;
  inline bool has_failed() const;
  inline void clear_failed();
  static const int kFailedFieldNumber = 6;
  inline bool failed() const;
  inline void set_failed(bool value);
  
  // optional string error_text = 7;
  inline bool has_error_text() const;
  inline void clear_error_text();
  static const int kErrorTextFieldNumber = 7;
  inline const ::std::string& error_text() const;
  inline void set_error_text(const ::std::string& value);
  inline void set_error_text(const char* value);
  inline void set_error_text(const char* value, size_t size);
  inline ::std::string* mutable_error_text();
  inline ::std::string* release_error_text();
  
  // @@protoc_insertion_point(class_scope:maid.controller.Controller)
 private:
  inline void set_has_service_name();
  inline void clear_has_service_name();
  inline void set_has_method_name();
  inline void clear_has_method_name();
  inline void set_has_transmit_id();
  inline void clear_has_transmit_id();
  inline void set_has_stub_side();
  inline void clear_has_stub_side();
  inline void set_has_is_canceled();
  inline void clear_has_is_canceled();
  inline void set_has_failed();
  inline void clear_has_failed();
  inline void set_has_error_text();
  inline void clear_has_error_text();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::std::string* service_name_;
  ::std::string* method_name_;
  ::google::protobuf::int32 transmit_id_;
  bool stub_side_;
  bool is_canceled_;
  bool failed_;
  ::std::string* error_text_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(7 + 31) / 32];
  
  friend void  protobuf_AddDesc_controller_2eproto();
  friend void protobuf_AssignDesc_controller_2eproto();
  friend void protobuf_ShutdownFile_controller_2eproto();
  
  void InitAsDefaultInstance();
  static Controller* default_instance_;
};
// ===================================================================


// ===================================================================

// Controller

// optional string service_name = 1;
inline bool Controller::has_service_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Controller::set_has_service_name() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Controller::clear_has_service_name() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Controller::clear_service_name() {
  if (service_name_ != &::google::protobuf::internal::kEmptyString) {
    service_name_->clear();
  }
  clear_has_service_name();
}
inline const ::std::string& Controller::service_name() const {
  return *service_name_;
}
inline void Controller::set_service_name(const ::std::string& value) {
  set_has_service_name();
  if (service_name_ == &::google::protobuf::internal::kEmptyString) {
    service_name_ = new ::std::string;
  }
  service_name_->assign(value);
}
inline void Controller::set_service_name(const char* value) {
  set_has_service_name();
  if (service_name_ == &::google::protobuf::internal::kEmptyString) {
    service_name_ = new ::std::string;
  }
  service_name_->assign(value);
}
inline void Controller::set_service_name(const char* value, size_t size) {
  set_has_service_name();
  if (service_name_ == &::google::protobuf::internal::kEmptyString) {
    service_name_ = new ::std::string;
  }
  service_name_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* Controller::mutable_service_name() {
  set_has_service_name();
  if (service_name_ == &::google::protobuf::internal::kEmptyString) {
    service_name_ = new ::std::string;
  }
  return service_name_;
}
inline ::std::string* Controller::release_service_name() {
  clear_has_service_name();
  if (service_name_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = service_name_;
    service_name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}

// optional string method_name = 2;
inline bool Controller::has_method_name() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Controller::set_has_method_name() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Controller::clear_has_method_name() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Controller::clear_method_name() {
  if (method_name_ != &::google::protobuf::internal::kEmptyString) {
    method_name_->clear();
  }
  clear_has_method_name();
}
inline const ::std::string& Controller::method_name() const {
  return *method_name_;
}
inline void Controller::set_method_name(const ::std::string& value) {
  set_has_method_name();
  if (method_name_ == &::google::protobuf::internal::kEmptyString) {
    method_name_ = new ::std::string;
  }
  method_name_->assign(value);
}
inline void Controller::set_method_name(const char* value) {
  set_has_method_name();
  if (method_name_ == &::google::protobuf::internal::kEmptyString) {
    method_name_ = new ::std::string;
  }
  method_name_->assign(value);
}
inline void Controller::set_method_name(const char* value, size_t size) {
  set_has_method_name();
  if (method_name_ == &::google::protobuf::internal::kEmptyString) {
    method_name_ = new ::std::string;
  }
  method_name_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* Controller::mutable_method_name() {
  set_has_method_name();
  if (method_name_ == &::google::protobuf::internal::kEmptyString) {
    method_name_ = new ::std::string;
  }
  return method_name_;
}
inline ::std::string* Controller::release_method_name() {
  clear_has_method_name();
  if (method_name_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = method_name_;
    method_name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}

// optional int32 transmit_id = 3;
inline bool Controller::has_transmit_id() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Controller::set_has_transmit_id() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Controller::clear_has_transmit_id() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Controller::clear_transmit_id() {
  transmit_id_ = 0;
  clear_has_transmit_id();
}
inline ::google::protobuf::int32 Controller::transmit_id() const {
  return transmit_id_;
}
inline void Controller::set_transmit_id(::google::protobuf::int32 value) {
  set_has_transmit_id();
  transmit_id_ = value;
}

// optional bool stub_side = 4;
inline bool Controller::has_stub_side() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void Controller::set_has_stub_side() {
  _has_bits_[0] |= 0x00000008u;
}
inline void Controller::clear_has_stub_side() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void Controller::clear_stub_side() {
  stub_side_ = false;
  clear_has_stub_side();
}
inline bool Controller::stub_side() const {
  return stub_side_;
}
inline void Controller::set_stub_side(bool value) {
  set_has_stub_side();
  stub_side_ = value;
}

// optional bool is_canceled = 5;
inline bool Controller::has_is_canceled() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void Controller::set_has_is_canceled() {
  _has_bits_[0] |= 0x00000010u;
}
inline void Controller::clear_has_is_canceled() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void Controller::clear_is_canceled() {
  is_canceled_ = false;
  clear_has_is_canceled();
}
inline bool Controller::is_canceled() const {
  return is_canceled_;
}
inline void Controller::set_is_canceled(bool value) {
  set_has_is_canceled();
  is_canceled_ = value;
}

// optional bool failed = 6;
inline bool Controller::has_failed() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void Controller::set_has_failed() {
  _has_bits_[0] |= 0x00000020u;
}
inline void Controller::clear_has_failed() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void Controller::clear_failed() {
  failed_ = false;
  clear_has_failed();
}
inline bool Controller::failed() const {
  return failed_;
}
inline void Controller::set_failed(bool value) {
  set_has_failed();
  failed_ = value;
}

// optional string error_text = 7;
inline bool Controller::has_error_text() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void Controller::set_has_error_text() {
  _has_bits_[0] |= 0x00000040u;
}
inline void Controller::clear_has_error_text() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void Controller::clear_error_text() {
  if (error_text_ != &::google::protobuf::internal::kEmptyString) {
    error_text_->clear();
  }
  clear_has_error_text();
}
inline const ::std::string& Controller::error_text() const {
  return *error_text_;
}
inline void Controller::set_error_text(const ::std::string& value) {
  set_has_error_text();
  if (error_text_ == &::google::protobuf::internal::kEmptyString) {
    error_text_ = new ::std::string;
  }
  error_text_->assign(value);
}
inline void Controller::set_error_text(const char* value) {
  set_has_error_text();
  if (error_text_ == &::google::protobuf::internal::kEmptyString) {
    error_text_ = new ::std::string;
  }
  error_text_->assign(value);
}
inline void Controller::set_error_text(const char* value, size_t size) {
  set_has_error_text();
  if (error_text_ == &::google::protobuf::internal::kEmptyString) {
    error_text_ = new ::std::string;
  }
  error_text_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* Controller::mutable_error_text() {
  set_has_error_text();
  if (error_text_ == &::google::protobuf::internal::kEmptyString) {
    error_text_ = new ::std::string;
  }
  return error_text_;
}
inline ::std::string* Controller::release_error_text() {
  clear_has_error_text();
  if (error_text_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = error_text_;
    error_text_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace controller
}  // namespace maid

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_controller_2eproto__INCLUDED
