// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: maid/connection.proto

#ifndef PROTOBUF_maid_2fconnection_2eproto__INCLUDED
#define PROTOBUF_maid_2fconnection_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "maid/controller.pb.h"
// @@protoc_insertion_point(includes)

namespace maid {
namespace proto {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_maid_2fconnection_2eproto();
void protobuf_AssignDesc_maid_2fconnection_2eproto();
void protobuf_ShutdownFile_maid_2fconnection_2eproto();

class ConnectionProto;

// ===================================================================

class ConnectionProto : public ::google::protobuf::Message {
 public:
  ConnectionProto();
  virtual ~ConnectionProto();

  ConnectionProto(const ConnectionProto& from);

  inline ConnectionProto& operator=(const ConnectionProto& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ConnectionProto& default_instance();

  void Swap(ConnectionProto* other);

  // implements Message ----------------------------------------------

  ConnectionProto* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ConnectionProto& from);
  void MergeFrom(const ConnectionProto& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int64 id = 1;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 1;
  inline ::google::protobuf::int64 id() const;
  inline void set_id(::google::protobuf::int64 value);

  // optional string host = 2;
  inline bool has_host() const;
  inline void clear_host();
  static const int kHostFieldNumber = 2;
  inline const ::std::string& host() const;
  inline void set_host(const ::std::string& value);
  inline void set_host(const char* value);
  inline void set_host(const char* value, size_t size);
  inline ::std::string* mutable_host();
  inline ::std::string* release_host();
  inline void set_allocated_host(::std::string* host);

  // optional int32 port = 3;
  inline bool has_port() const;
  inline void clear_port();
  static const int kPortFieldNumber = 3;
  inline ::google::protobuf::int32 port() const;
  inline void set_port(::google::protobuf::int32 value);

  GOOGLE_PROTOBUF_EXTENSION_ACCESSORS(ConnectionProto)
  // @@protoc_insertion_point(class_scope:maid.proto.ConnectionProto)
 private:
  inline void set_has_id();
  inline void clear_has_id();
  inline void set_has_host();
  inline void clear_has_host();
  inline void set_has_port();
  inline void clear_has_port();

  ::google::protobuf::internal::ExtensionSet _extensions_;

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int64 id_;
  ::std::string* host_;
  ::google::protobuf::int32 port_;
  friend void  protobuf_AddDesc_maid_2fconnection_2eproto();
  friend void protobuf_AssignDesc_maid_2fconnection_2eproto();
  friend void protobuf_ShutdownFile_maid_2fconnection_2eproto();

  void InitAsDefaultInstance();
  static ConnectionProto* default_instance_;
};
// ===================================================================

static const int kConnectionFieldNumber = 1001;
extern ::google::protobuf::internal::ExtensionIdentifier< ::maid::proto::ControllerProto,
    ::google::protobuf::internal::MessageTypeTraits< ::maid::proto::ConnectionProto >, 11, false >
  connection;

// ===================================================================

// ConnectionProto

// optional int64 id = 1;
inline bool ConnectionProto::has_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ConnectionProto::set_has_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ConnectionProto::clear_has_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ConnectionProto::clear_id() {
  id_ = GOOGLE_LONGLONG(0);
  clear_has_id();
}
inline ::google::protobuf::int64 ConnectionProto::id() const {
  // @@protoc_insertion_point(field_get:maid.proto.ConnectionProto.id)
  return id_;
}
inline void ConnectionProto::set_id(::google::protobuf::int64 value) {
  set_has_id();
  id_ = value;
  // @@protoc_insertion_point(field_set:maid.proto.ConnectionProto.id)
}

// optional string host = 2;
inline bool ConnectionProto::has_host() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ConnectionProto::set_has_host() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ConnectionProto::clear_has_host() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ConnectionProto::clear_host() {
  if (host_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    host_->clear();
  }
  clear_has_host();
}
inline const ::std::string& ConnectionProto::host() const {
  // @@protoc_insertion_point(field_get:maid.proto.ConnectionProto.host)
  return *host_;
}
inline void ConnectionProto::set_host(const ::std::string& value) {
  set_has_host();
  if (host_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    host_ = new ::std::string;
  }
  host_->assign(value);
  // @@protoc_insertion_point(field_set:maid.proto.ConnectionProto.host)
}
inline void ConnectionProto::set_host(const char* value) {
  set_has_host();
  if (host_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    host_ = new ::std::string;
  }
  host_->assign(value);
  // @@protoc_insertion_point(field_set_char:maid.proto.ConnectionProto.host)
}
inline void ConnectionProto::set_host(const char* value, size_t size) {
  set_has_host();
  if (host_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    host_ = new ::std::string;
  }
  host_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:maid.proto.ConnectionProto.host)
}
inline ::std::string* ConnectionProto::mutable_host() {
  set_has_host();
  if (host_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    host_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:maid.proto.ConnectionProto.host)
  return host_;
}
inline ::std::string* ConnectionProto::release_host() {
  clear_has_host();
  if (host_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = host_;
    host_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void ConnectionProto::set_allocated_host(::std::string* host) {
  if (host_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete host_;
  }
  if (host) {
    set_has_host();
    host_ = host;
  } else {
    clear_has_host();
    host_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:maid.proto.ConnectionProto.host)
}

// optional int32 port = 3;
inline bool ConnectionProto::has_port() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void ConnectionProto::set_has_port() {
  _has_bits_[0] |= 0x00000004u;
}
inline void ConnectionProto::clear_has_port() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void ConnectionProto::clear_port() {
  port_ = 0;
  clear_has_port();
}
inline ::google::protobuf::int32 ConnectionProto::port() const {
  // @@protoc_insertion_point(field_get:maid.proto.ConnectionProto.port)
  return port_;
}
inline void ConnectionProto::set_port(::google::protobuf::int32 value) {
  set_has_port();
  port_ = value;
  // @@protoc_insertion_point(field_set:maid.proto.ConnectionProto.port)
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace proto
}  // namespace maid

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_maid_2fconnection_2eproto__INCLUDED
