// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: maid/options.proto

#ifndef PROTOBUF_maid_2foptions_2eproto__INCLUDED
#define PROTOBUF_maid_2foptions_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "google/protobuf/descriptor.pb.h"
// @@protoc_insertion_point(includes)

namespace maid {
namespace proto {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_maid_2foptions_2eproto();
void protobuf_AssignDesc_maid_2foptions_2eproto();
void protobuf_ShutdownFile_maid_2foptions_2eproto();

class MaidServiceOptions;
class MaidMethodOptions;

// ===================================================================

class MaidServiceOptions : public ::google::protobuf::Message {
 public:
  MaidServiceOptions();
  virtual ~MaidServiceOptions();

  MaidServiceOptions(const MaidServiceOptions& from);

  inline MaidServiceOptions& operator=(const MaidServiceOptions& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MaidServiceOptions& default_instance();

  void Swap(MaidServiceOptions* other);

  // implements Message ----------------------------------------------

  inline MaidServiceOptions* New() const { return New(NULL); }

  MaidServiceOptions* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MaidServiceOptions& from);
  void MergeFrom(const MaidServiceOptions& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(MaidServiceOptions* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional bool notify = 1;
  inline bool has_notify() const;
  inline void clear_notify();
  static const int kNotifyFieldNumber = 1;
  inline bool notify() const;
  inline void set_notify(bool value);

  // @@protoc_insertion_point(class_scope:maid.proto.MaidServiceOptions)
 private:
  inline void set_has_notify();
  inline void clear_has_notify();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  bool notify_;
  friend void  protobuf_AddDesc_maid_2foptions_2eproto();
  friend void protobuf_AssignDesc_maid_2foptions_2eproto();
  friend void protobuf_ShutdownFile_maid_2foptions_2eproto();

  void InitAsDefaultInstance();
  static MaidServiceOptions* default_instance_;
};
// -------------------------------------------------------------------

class MaidMethodOptions : public ::google::protobuf::Message {
 public:
  MaidMethodOptions();
  virtual ~MaidMethodOptions();

  MaidMethodOptions(const MaidMethodOptions& from);

  inline MaidMethodOptions& operator=(const MaidMethodOptions& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MaidMethodOptions& default_instance();

  void Swap(MaidMethodOptions* other);

  // implements Message ----------------------------------------------

  inline MaidMethodOptions* New() const { return New(NULL); }

  MaidMethodOptions* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MaidMethodOptions& from);
  void MergeFrom(const MaidMethodOptions& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(MaidMethodOptions* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional bool notify = 1;
  inline bool has_notify() const;
  inline void clear_notify();
  static const int kNotifyFieldNumber = 1;
  inline bool notify() const;
  inline void set_notify(bool value);

  // optional int64 time_out = 2 [default = -1];
  inline bool has_time_out() const;
  inline void clear_time_out();
  static const int kTimeOutFieldNumber = 2;
  inline ::google::protobuf::int64 time_out() const;
  inline void set_time_out(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:maid.proto.MaidMethodOptions)
 private:
  inline void set_has_notify();
  inline void clear_has_notify();
  inline void set_has_time_out();
  inline void clear_has_time_out();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int64 time_out_;
  bool notify_;
  friend void  protobuf_AddDesc_maid_2foptions_2eproto();
  friend void protobuf_AssignDesc_maid_2foptions_2eproto();
  friend void protobuf_ShutdownFile_maid_2foptions_2eproto();

  void InitAsDefaultInstance();
  static MaidMethodOptions* default_instance_;
};
// ===================================================================

static const int kServiceOptionsFieldNumber = 1001;
extern ::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::ServiceOptions,
    ::google::protobuf::internal::MessageTypeTraits< ::maid::proto::MaidServiceOptions >, 11, false >
  service_options;
static const int kMethodOptionsFieldNumber = 1001;
extern ::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::MethodOptions,
    ::google::protobuf::internal::MessageTypeTraits< ::maid::proto::MaidMethodOptions >, 11, false >
  method_options;

// ===================================================================

// MaidServiceOptions

// optional bool notify = 1;
inline bool MaidServiceOptions::has_notify() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MaidServiceOptions::set_has_notify() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MaidServiceOptions::clear_has_notify() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MaidServiceOptions::clear_notify() {
  notify_ = false;
  clear_has_notify();
}
inline bool MaidServiceOptions::notify() const {
  // @@protoc_insertion_point(field_get:maid.proto.MaidServiceOptions.notify)
  return notify_;
}
inline void MaidServiceOptions::set_notify(bool value) {
  set_has_notify();
  notify_ = value;
  // @@protoc_insertion_point(field_set:maid.proto.MaidServiceOptions.notify)
}

// -------------------------------------------------------------------

// MaidMethodOptions

// optional bool notify = 1;
inline bool MaidMethodOptions::has_notify() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MaidMethodOptions::set_has_notify() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MaidMethodOptions::clear_has_notify() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MaidMethodOptions::clear_notify() {
  notify_ = false;
  clear_has_notify();
}
inline bool MaidMethodOptions::notify() const {
  // @@protoc_insertion_point(field_get:maid.proto.MaidMethodOptions.notify)
  return notify_;
}
inline void MaidMethodOptions::set_notify(bool value) {
  set_has_notify();
  notify_ = value;
  // @@protoc_insertion_point(field_set:maid.proto.MaidMethodOptions.notify)
}

// optional int64 time_out = 2 [default = -1];
inline bool MaidMethodOptions::has_time_out() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void MaidMethodOptions::set_has_time_out() {
  _has_bits_[0] |= 0x00000002u;
}
inline void MaidMethodOptions::clear_has_time_out() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void MaidMethodOptions::clear_time_out() {
  time_out_ = GOOGLE_LONGLONG(-1);
  clear_has_time_out();
}
inline ::google::protobuf::int64 MaidMethodOptions::time_out() const {
  // @@protoc_insertion_point(field_get:maid.proto.MaidMethodOptions.time_out)
  return time_out_;
}
inline void MaidMethodOptions::set_time_out(::google::protobuf::int64 value) {
  set_has_time_out();
  time_out_ = value;
  // @@protoc_insertion_point(field_set:maid.proto.MaidMethodOptions.time_out)
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace proto
}  // namespace maid

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace protobuf
}  // namespace google
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_maid_2foptions_2eproto__INCLUDED
