# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: maid/connection.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='maid/connection.proto',
  package='maid.proto',
  syntax='proto3',
  serialized_pb=b'\n\x15maid/connection.proto\x12\nmaid.proto\"9\n\x0f\x43onnectionProto\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0c\n\x04host\x18\x02 \x01(\t\x12\x0c\n\x04port\x18\x03 \x01(\x05\x62\x06proto3'
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_CONNECTIONPROTO = _descriptor.Descriptor(
  name='ConnectionProto',
  full_name='maid.proto.ConnectionProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='maid.proto.ConnectionProto.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='host', full_name='maid.proto.ConnectionProto.host', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='port', full_name='maid.proto.ConnectionProto.port', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=37,
  serialized_end=94,
)

DESCRIPTOR.message_types_by_name['ConnectionProto'] = _CONNECTIONPROTO

ConnectionProto = _reflection.GeneratedProtocolMessageType('ConnectionProto', (_message.Message,), dict(
  DESCRIPTOR = _CONNECTIONPROTO,
  __module__ = 'maid.connection_pb2'
  # @@protoc_insertion_point(class_scope:maid.proto.ConnectionProto)
  ))
_sym_db.RegisterMessage(ConnectionProto)


# @@protoc_insertion_point(module_scope)
