# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: maid/session.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='maid/session.proto',
  package='maid.proto',
  syntax='proto2',
  serialized_pb=_b('\n\x12maid/session.proto\x12\nmaid.proto\"0\n\x0cSessionProto\x12\n\n\x02id\x18\x01 \x01(\t\x12\x14\n\x0c\x65xpired_time\x18\x02 \x01(\x04')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_SESSIONPROTO = _descriptor.Descriptor(
  name='SessionProto',
  full_name='maid.proto.SessionProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='maid.proto.SessionProto.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='expired_time', full_name='maid.proto.SessionProto.expired_time', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=82,
)

DESCRIPTOR.message_types_by_name['SessionProto'] = _SESSIONPROTO

SessionProto = _reflection.GeneratedProtocolMessageType('SessionProto', (_message.Message,), dict(
  DESCRIPTOR = _SESSIONPROTO,
  __module__ = 'maid.session_pb2'
  # @@protoc_insertion_point(class_scope:maid.proto.SessionProto)
  ))
_sym_db.RegisterMessage(SessionProto)


# @@protoc_insertion_point(module_scope)
