# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='hello.proto',
  package='',
  serialized_pb='\n\x0bhello.proto\"\x05\n\x03Say\"\x07\n\x05Hello2#\n\x0b\x45\x63hoService\x12\x14\n\x04\x45\x63ho\x12\x04.Say\x1a\x06.HelloB\x03\x80\x01\x01')




_SAY = descriptor.Descriptor(
  name='Say',
  full_name='Say',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=15,
  serialized_end=20,
)


_HELLO = descriptor.Descriptor(
  name='Hello',
  full_name='Hello',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=22,
  serialized_end=29,
)

DESCRIPTOR.message_types_by_name['Say'] = _SAY
DESCRIPTOR.message_types_by_name['Hello'] = _HELLO

class Say(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SAY
  
  # @@protoc_insertion_point(class_scope:Say)

class Hello(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _HELLO
  
  # @@protoc_insertion_point(class_scope:Hello)

# @@protoc_insertion_point(module_scope)
