//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: proto/controller.proto
namespace maid.proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ControllerMeta")]
  public partial class ControllerMeta : global::ProtoBuf.IExtensible
  {
    public ControllerMeta() {}
    
    private string _method_name = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"method_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string method_name
    {
      get { return _method_name; }
      set { _method_name = value; }
    }
    private uint _transmit_id = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"transmit_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint transmit_id
    {
      get { return _transmit_id; }
      set { _transmit_id = value; }
    }
    private bool _stub = default(bool);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"stub", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool stub
    {
      get { return _stub; }
      set { _stub = value; }
    }
    private bool _is_canceled = default(bool);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"is_canceled", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool is_canceled
    {
      get { return _is_canceled; }
      set { _is_canceled = value; }
    }
    private bool _failed = default(bool);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"failed", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool failed
    {
      get { return _failed; }
      set { _failed = value; }
    }
    private string _error_text = "";
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"error_text", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string error_text
    {
      get { return _error_text; }
      set { _error_text = value; }
    }
    private bool _notify = default(bool);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"notify", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool notify
    {
      get { return _notify; }
      set { _notify = value; }
    }
    private byte[] _message = null;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"message", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] message
    {
      get { return _message; }
      set { _message = value; }
    }
    private string _full_service_name = "";
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"full_service_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string full_service_name
    {
      get { return _full_service_name; }
      set { _full_service_name = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}